# Generated by Django 5.1.15 on 2026-08-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_fetch_runs_and_rich_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='extras',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='rawpage',
            index=models.Index(fields=['created_at'], name='tweets_rawp_created_91958e_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['-created_at', '-id'], name='tweets_twee_created_a7441d_idx'),
        ),
    ]
