# Generated by Django 5.1.15 on 2026-08-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='observed_median_gap_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='poll_interval_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
