# Generated by Django 5.1.15 on 2026-08-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0012_account_poll_cadence'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='interval_seconds',
            field=models.PositiveIntegerField(default=1800),
        ),
    ]
