# Generated by Django 5.1.15 on 2026-08-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0013_search_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='source_subsystem',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['-ingested_at'], name='tweets_twee_ingeste_ee8936_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['source_subsystem', '-ingested_at'], name='tweets_twee_source__420aca_idx'),
        ),
    ]
