# Generated by Django 5.1.15 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0014_tweet_source_subsystem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("remote_url", models.URLField(max_length=1000, unique=True)),
                ("relative_path", models.CharField(max_length=400)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_ok_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
