# Generated by Django 5.1.15 on 2026-08-28 20:34

from django.db import migrations, models

from tweets.textclean import clean_text

BATCH = 2000


def _backfill(apps, schema_editor):
    """Derive text_clean for rows that predate the column.

    Batched with a bounded update list rather than one .save() per row: the
    archive is ~53k rows and growing, and a per-row round trip turns a migration
    into a several-minute outage on deploy.
    """
    for label in ("Tweet", "SearchTweet"):
        model = apps.get_model("tweets", label)
        pending = []
        for pk, raw in model.objects.filter(text_clean="").values_list("id", "text").iterator(
            chunk_size=BATCH
        ):
            cleaned = clean_text(raw)
            if not cleaned:
                continue
            pending.append(model(id=pk, text_clean=cleaned))
            if len(pending) >= BATCH:
                model.objects.bulk_update(pending, ["text_clean"])
                pending = []
        if pending:
            model.objects.bulk_update(pending, ["text_clean"])


def _noop(apps, schema_editor):
    """Reversing only drops the column, which RemoveField already does."""


def _index(apps, schema_editor):
    """Trigram index for the archive search box.

    Archive search is `text_clean ILIKE '%q%'`, and on PostgreSQL Django emits a
    literal ILIKE, which `gin_trgm_ops` on the plain column can serve. Indexing
    lower(text_clean) instead -- as migration 0011 did for narratives -- would not
    be used by this query at all.
    """
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    for table in ("tweets_tweet", "tweets_searchtweet"):
        schema_editor.execute(
            f"CREATE INDEX IF NOT EXISTS {table}_text_clean_trgm "
            f"ON {table} USING GIN (text_clean gin_trgm_ops);"
        )


def _drop_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for table in ("tweets_tweet", "tweets_searchtweet"):
        schema_editor.execute(f"DROP INDEX IF EXISTS {table}_text_clean_trgm;")


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0016_search_domain_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtweet',
            name='text_clean',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tweet',
            name='text_clean',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(_backfill, _noop),
        migrations.RunPython(_index, _drop_index),
    ]
