# Generated by Django 5.1.15 on 2026-09-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0017_text_clean'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tweetmetric',
            index=models.Index(fields=['captured_at'], name='tweets_metric_captured_idx'),
        ),
    ]
