# Generated by Django 5.1.15 on 2026-09-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0021_export_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_url', models.URLField(max_length=1000, unique=True)),
                ('tweet_id', models.CharField(blank=True, default='', max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['attempts', 'id'], name='tweets_pendingmedia_idx')],
            },
        ),
    ]
