# Generated by Django 5.1.15 on 2026-07-21 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=100, unique=True)),
                ('rest_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('tracking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='XSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=64, unique=True)),
                ('cookies', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EndpointState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(db_index=True, max_length=120)),
                ('endpoint', models.CharField(db_index=True, max_length=64)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('account', 'endpoint')},
            },
        ),
        migrations.CreateModel(
            name='KeyValueState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('namespace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RawPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=64)),
                ('account', models.CharField(db_index=True, max_length=120)),
                ('batch', models.CharField(db_index=True, max_length=200)),
                ('page_number', models.IntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('endpoint', 'account', 'batch', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('raw_query', models.TextField()),
                ('product', models.CharField(choices=[('Top', 'Top'), ('Latest', 'Latest')], default='Top', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('slug', 'product', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedup_key', models.CharField(max_length=160, unique=True)),
                ('tweet_id', models.CharField(db_index=True, max_length=64)),
                ('author_rest_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('account', models.CharField(db_index=True, max_length=100)),
                ('text', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('type', models.CharField(default='Tweet', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('raw_created_at', models.CharField(blank=True, default='', max_length=64)),
                ('likes', models.BigIntegerField(default=0)),
                ('retweets', models.BigIntegerField(default=0)),
                ('replies', models.BigIntegerField(default=0)),
                ('quotes', models.BigIntegerField(default=0)),
                ('bookmarks', models.BigIntegerField(default=0)),
                ('views', models.BigIntegerField(default=0)),
                ('source_language', models.CharField(blank=True, max_length=16, null=True)),
                ('source_endpoint', models.CharField(blank=True, default='', max_length=64)),
                ('conversation_id', models.CharField(blank=True, max_length=64, null=True)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tweets', to='tweets.twitteruser')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tweets.search')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='tweets.tweet')),
            ],
            options={
                'ordering': ['rank', '-id'],
                'unique_together': {('search', 'tweet')},
            },
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['account', '-created_at'], name='tweets_twee_account_c693b4_idx'),
        ),
    ]
