# Generated by Django 5.1.15 on 2026-08-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_search_depth_and_normalize_handles'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsession',
            name='config_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
