# Generated by Django 5.1.15 on 2026-08-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_xsession_config_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='rolling_hours',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
