# Generated by Django 5.1.15 on 2026-07-21 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='tweets.twitteruser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'account')},
            },
        ),
        migrations.CreateModel(
            name='SearchSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='tweets.search')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_subs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'search')},
            },
        ),
    ]
